Scale flux for conditions
cta-observatory/pyirf pull request #104
Opened 2020-10-15 09:27 UTC by maxnoe

2020-11-05 14:24 UTC, moralejo commented on pyirf/sensitivity.py
> +    # less then min_sigma
than

2020-11-05 14:26 UTC, moralejo approved these changes

2020-11-06 10:06 UTC, HealthyPear requested changes

2020-11-06 10:23 UTC, maxnoe commented on examples/calculate_eventdisplay_irfs.py
>          theta_cuts=theta_cuts,
yes it is.  But I found that the cuts below are not used. So I started at `-0.5` to reduce the load a bit.

2020-11-06 10:23 UTC, maxnoe commented on .travis.yml
> +  - pip install travis-sphinx
yes, will fix.

2020-11-06 10:23 UTC, maxnoe commented on pyirf/io/gadf.py
> +    print(psf['RPSF'].shape)
yes.

2020-11-06 11:17 UTC, HealthyPear approved these changes

2020-11-06 11:17 UTC, merged