Enable intersphinx, use to link to gammapy docs
cta-observatory/pyirf pull request #168
Opened 2021-11-29 15:16 UTC by maxnoe

2021-12-01 18:03 UTC, HealthyPear requested changes

2021-12-01 18:03 UTC, HealthyPear commented on pyirf/gammapy.py
> +    Create a :py:class`gammapy.irf.EnergyDispersion2D` from pyirf outputs.
Apart from the merging conflicts, there is onlny a typo here,

`:py:class`**:**

2021-12-03 17:20 UTC, maxnoe commented
@HealthyPear fixed

2022-01-10 10:08 UTC, HealthyPear approved these changes

2022-01-10 10:13 UTC, merged