Feature resample histogram
cta-observatory/pyirf pull request #72
Opened 2020-09-29 15:34 UTC by nbiederbeck

supersedes #64 and adds #49

2020-09-29 15:41 UTC, nbiederbeck commented
I am trying ..

2020-09-29 15:41 UTC, MaxNoe commented on pyirf/binning.py
> +def resample_histogram(data, old_edges, new_edges, axis=0):
maybe add a `1d`?

2020-09-29 15:42 UTC, MaxNoe commented on docs/irf/index.rst
> +The corresponding, sparse energy migration matrix can be build from the dispersion matrix.
Sparse is not part of the definion. it's more like an expected property of the migration matrix.

The real difference is in the second axis: dispersion as `(e_reco / e_true)` , migration has `e_reco`

2020-09-29 16:26 UTC, MaxNoe requested changes
Please add a test and fix the behaviour for bins that include under/overflow bin.

When I tested this locally with edisp that had under/overflow bins, all migration bins were `np.nan`

2020-09-30 12:01 UTC, nbiederbeck commented
> Does this now mean it is required to have an overflow bin?

No. There is a test with and without overflow bins. `np.nan_to_num` does nothing if there are no over/underflow bins

> And shouldn't it be `old_edges[-1]`?

`old_edges[-1] == np.inf` (with overflow bins), so we chose the second last bin which is not inf

2020-09-30 12:03 UTC, nbiederbeck commented
Travis still fails while downloading the test data

2020-09-30 12:16 UTC, MaxNoe commented
Ah, dam, this is because PRs from forks don't have access to the credentials.

2020-09-30 12:19 UTC, HealthyPear commented
> Ah, dam, this is because PRs from forks don't have access to the credentials.

Pardon my ignorance, but why would it matter?
Isn't this password just a string? if one has it it downloads otherwise not
or there is some other linked with information with it?

2020-09-30 12:22 UTC, MaxNoe commented
The download needs a password. That password is stored using travis' credential system. 

Build from pull requests don't have access to these credentials, because they could just add something like `echo $PASSWORD` to the .travis.yml to get the password.

So, only builds from the repo itself have access to these credentials for security reasons.

2020-09-30 12:22 UTC, nbiederbeck commented
after pushing to the main repo I need to open another PR ?

2020-09-30 12:23 UTC, MaxNoe commented
Probably, yes. I don't think there is the possibility to change the branch of a PR

2020-09-30 18:53 UTC, closed without merging